import { Card } from "../types";

const cards: Card[] = [
  { name: "2h", color: "heart", value: 2, taken: false },
  { name: "3h", color: "heart", value: 3, taken: false },
  { name: "4h", color: "heart", value: 4, taken: false },
  { name: "5h", color: "heart", value: 5, taken: false },
  { name: "6h", color: "heart", value: 6, taken: false },
  { name: "7h", color: "heart", value: 7, taken: false },
  { name: "8h", color: "heart", value: 8, taken: false },
  { name: "9h", color: "heart", value: 9, taken: false },
  { name: "Th", color: "heart", value: 10, taken: false },
  { name: "Jh", color: "heart", value: 11, taken: false },
  { name: "Qh", color: "heart", value: 12, taken: false },
  { name: "Kh", color: "heart", value: 13, taken: false },
  { name: "Ah", color: "heart", value: 14, taken: false },
  { name: "2s", color: "spade", value: 2, taken: false },
  { name: "3s", color: "spade", value: 3, taken: false },
  { name: "4s", color: "spade", value: 4, taken: false },
  { name: "5s", color: "spade", value: 5, taken: false },
  { name: "6s", color: "spade", value: 6, taken: false },
  { name: "7s", color: "spade", value: 7, taken: false },
  { name: "8s", color: "spade", value: 8, taken: false },
  { name: "9s", color: "spade", value: 9, taken: false },
  { name: "Ts", color: "spade", value: 10, taken: false },
  { name: "Js", color: "spade", value: 11, taken: false },
  { name: "Qs", color: "spade", value: 12, taken: false },
  { name: "Ks", color: "spade", value: 13, taken: false },
  { name: "As", color: "spade", value: 14, taken: false },
  { name: "2c", color: "club", value: 2, taken: false },
  { name: "3c", color: "club", value: 3, taken: false },
  { name: "4c", color: "club", value: 4, taken: false },
  { name: "5c", color: "club", value: 5, taken: false },
  { name: "6c", color: "club", value: 6, taken: false },
  { name: "7c", color: "club", value: 7, taken: false },
  { name: "8c", color: "club", value: 8, taken: false },
  { name: "9c", color: "club", value: 9, taken: false },
  { name: "Tc", color: "club", value: 10, taken: false },
  { name: "Jc", color: "club", value: 11, taken: false },
  { name: "Qc", color: "club", value: 12, taken: false },
  { name: "Kc", color: "club", value: 13, taken: false },
  { name: "Ac", color: "club", value: 14, taken: false },
  { name: "2d", color: "diamond", value: 2, taken: false },
  { name: "3d", color: "diamond", value: 3, taken: false },
  { name: "4d", color: "diamond", value: 4, taken: false },
  { name: "5d", color: "diamond", value: 5, taken: false },
  { name: "6d", color: "diamond", value: 6, taken: false },
  { name: "7d", color: "diamond", value: 7, taken: false },
  { name: "8d", color: "diamond", value: 8, taken: false },
  { name: "9d", color: "diamond", value: 9, taken: false },
  { name: "Td", color: "diamond", value: 10, taken: false },
  { name: "Jd", color: "diamond", value: 11, taken: false },
  { name: "Qd", color: "diamond", value: 12, taken: false },
  { name: "Kd", color: "diamond", value: 13, taken: false },
  { name: "Ad", color: "diamond", value: 14, taken: false },
];

export default cards;
